name: Main

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build --no-restore --no-dependencies

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Bump version
      id: version
      run: echo "v$(($(git describe --tags --abbrev=0 | tr -d 'v') + 1))" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      run: echo "## Release ${{ steps.version.outputs.version }}" > changelog.md

    - name: Commit and tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add changelog.md
        git commit -m "chore(release): v${{ steps.version.outputs.version }}"
        git tag "v${{ steps.version.outputs.version }}"

    - name: Push to Release
      run: git push origin "v${{ steps.version.outputs.version }}"
