name: Main

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
    - name: Build
      run: dotnet build --no-restore --no-dependencies --ignore-failed-sources
